[project]
name = "home-langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "homeassistant>=2025.4.4",
    "nabu-agent",
]

[tool.uv.sources]
nabu-agent = { git = "https://github.com/und1n3/nabu-agent" }
